# Production-specific config
version: '3'
services:
  web:
    ports: ['0.0.0.0:80:8080']
    volumes:
    - ./web/prod.conf:/etc/nginx/conf.d/smartroadsense.conf:ro
    - /tmp/tiles:/tmp/tiles:rw
    - /tmp/osm_tiles:/tmp/osm_tiles:rw

  ui:
    environment:
    - HUGO_BASEURL=http://www.smartroadsense.it/

  agg-web:
    ports: ['127.0.0.1:9001:80']

  raw-web:
    ports: ['127.0.0.1:9002:80']
