# Production-specific config
version: '3'
services:
  web:
    volumes:
    - ./web/prod.conf:/etc/nginx/conf.d/smartroadsense.conf:ro
    - /tmp/tiles:/tmp/tiles:rw
    - /tmp/osm_tiles:/tmp/osm_tiles:rw
    restart: unless-stopped

  tiles:
    restart: unless-stopped

  agg-web:
    restart: unless-stopped

  bb:
    restart: unless-stopped

  ws:
    restart: unless-stopped

  api:
    restart: unless-stopped

  raw-web:
    restart: unless-stopped

  webhookmonitor:
    environment:
    - ENV=prod
    restart: unless-stopped
