# Common config
version: '2'
volumes:
  web_data: {}
services:
  web:
    container_name: web
    build: ./web
    volumes:
    - web_data:/www:ro
    - ./data:/data:ro
    depends_on:
    - tiles
    - ui
    - ws
    - api
    restart: always

  ui:
    container_name: ui
    build: ./ui
    volumes:
      - web_data:/code:rw

  tiles:
    container_name: tiles
    build: ./tiles
    command: nodemon server.js
    volumes: ['./tiles:/code:ro']
    ports: ['127.0.0.1:8000:8000']
    depends_on: [ws]
    restart: always

  agg-cli:
    container_name: agg-cli
    build: ./agg/cli
    volumes:
    - ./agg/cli:/code:rw
    - ./data:/data:rw

  agg-web:
    container_name: agg-web
    build: ./agg/web
    restart: always

  raw-cli:
    container_name: raw-cli
    build: ./raw/cli
    volumes: ['./raw/cli:/code:rw', './data:/data:rw']

  raw-web:
    container_name: raw-web
    build: ./raw/web
    restart: always
    restart: always

  ws:
    container_name: ws
    build: ./ws
    volumes: ['./ws:/code/ws:rw']
    restart: always

  api:
    container_name: api
    build: ./api
    volumes: ['./api:/code/api:rw']
    restart: always
    restart: always

  map-reduce:
    container_name: map-reduce
    build: ./jobs/map-reduce
    volumes: ['./jobs/map-reduce:/code:ro']

  meta-updater:
    container_name: meta-updater
    build: ./jobs/meta-updater/
    volumes: ['./jobs/meta-updater:/code:ro']
