# Production-specific config
version: '2'
services:
  web:
    ports: ['0.0.0.0:80:8080']
    volumes:
    - ./web/prod.conf:/etc/nginx/conf.d/smartroadsense.conf:ro
    - /tmp/tiles:/tmp/tiles:rw
    - /tmp/osm_tiles:/tmp/osm_tiles:rw

  tiles:
    env_file: config.env
  ui:
    environment:
    - HUGO_BASEURL=http://www.smartroadsense.it/

  agg-cli:
    env_file: config.env
  agg-web:
    ports: ['0.0.0.0:9001:80']
    env_file: config.env

  raw-cli:
    env_file: config.env
  raw-web:
    ports: ['0.0.0.0:9002:80']
    env_file: config.env

  ws:
    env_file: config.env

  api:
    env_file: config.env

  map-reduce:
    env_file: config.env

  meta-updater:
    env_file: config.env
